### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by mrbll48** [mrbll48/workout-tracker#25]
Backend:
- Logout route
- Add comments to workouts
- Likes on workouts

Frontend: 
- fix boxcomponent.js
- connect backend to front end
- workout API on front end
- make component to display API data

**Comment by mrbll48** [comment]
I will work on logout route

**Comment by JairGH** [comment]
I will work on the box component.

**Comment by mrbll48** [comment]
add comments to workouts done on backend
